#!/usr/bin/env python3

import pandas as pd
import requests
from pprint import pprint
import time
from tqdm import tqdm
#!API hidden in public board
BASE_URL = "http://archive..org/_/api/search/"
RATE_LIMIT = 60 / 5 # Search API is limited to 5 requests per minute
df = pd.DataFrame()

try:
    for page in tqdm(range(1, 4000)):
        while True:
            try:
                r = requests.get(BASE_URL, params={
                    "boards": "monday",
                    "country": "NZ",
                    "page": page,
                    "end": "2021-06-23"
                }, headers={
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
                })
                r.raise_for_status()
                break
            except Exception as e:
                if r.status_code == 429:
                    retry_after = int(r.headers.get("Retry-After", 5))
                    print(f"ERROR: {e}. Retrying in {retry_after}s")
                    time.sleep(retry_after)
                else:
                    print(f"ERROR: {e}. Retrying in 5s")
                    time.sleep(5)

        df = df.append(pd.json_normalize(r.json()["0"]["posts"]))
        time.sleep(RATE_LIMIT)
except KeyboardInterrupt:
    print("Interrupted by user, will now save")
except Exception as e:
    print(e)

df = df.drop_duplicates()
df.to_csv("nz_20.csv", index=False)
print("Done")
